#!/bin/sh
# test-grok-runtime.sh — RUNTIME proof of the M6 (hermetic) isolation in grok_relay / grok_media.
# ---------------------------------------------------------------------------------------
# Runtime counterpart to scripts/regression-grok-safety.sh (a STATIC text tripwire). This script:
#   1. Extracts the REAL grok_relay/grok_media from ../SKILL.md at runtime (by pattern, never by
#      line number) so it always tests the shipped code.
#   2. Generates a self-contained FAKE `grok` and puts it FIRST on a minimal PATH that EXCLUDES the
#      dirs a real grok lives in (~/.local/bin, ~/.grok/bin, homebrew, npm-global). The real grok /
#      network / xAI is NEVER touched. Because the helper's `env -i` strips env vars, the fake cannot
#      rely on an env sentinel — it self-identifies via a BAKED-IN absolute path and a FILE sentinel,
#      and REFUSES to run (exit 99) if that sentinel is absent (so a stray copy on a real PATH screams
#      instead of shadowing grok). A safety gate re-asserts `command -v grok` == the fake before every
#      scenario; if it ever resolves elsewhere the run ABORTS.
#   3. Runs a full isolation / lifecycle / publish matrix under sh + bash + zsh.
#   4. Proves each protection with mutation red-green testing on a COPY of the helpers (SKILL.md is
#      never modified).
#
# Everything runs under a private temp tree; the real ~/.grok, ~/.claude and the installed skill
# copies are never read or written. Synthetic data only; no token/key VALUE is ever written to a log.
#
# Exit 0 iff every scenario passed on every available shell AND every mutation was caught (red) while
# pristine passed (green). Missing shells are SKIPPED. NOTE: this proves the WRAPPER's isolation; it
# does NOT and cannot verify the shipped grok binary (unverifiable by design; see SECURITY.md).

set -u

# --------------------------------------------------------------------------- paths & setup
SELF=$0; case "$SELF" in /*) ;; *) SELF="$(pwd)/$SELF" ;; esac
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$SELF")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
SKILL="$REPO_ROOT/SKILL.md"
[ -f "$SKILL" ] || { echo "FATAL: SKILL.md not found at $SKILL" >&2; exit 2; }

_tmpbase=${TMPDIR:-/tmp}; _tmpbase=${_tmpbase%/}
WORK=$(mktemp -d "$_tmpbase/grok-runtime-test.XXXXXX") || { echo "FATAL: mktemp" >&2; exit 2; }
cleanup() { chmod -R u+rwx "$WORK" 2>/dev/null; rm -rf "$WORK" 2>/dev/null; }
trap 'cleanup' EXIT INT TERM HUP

FAKEBIN="$WORK/bin"; LOGDIR="$WORK/log"; DRIVER="$WORK/driver.sh"; PRISTINE="$WORK/helpers.pristine.sh"
RESULTS="$WORK/results.txt"; MUTLOG="$WORK/mutations.txt"
mkdir -p "$FAKEBIN" "$LOGDIR" "$WORK/runs" || { echo "FATAL: mkdir" >&2; exit 2; }
: > "$RESULTS"; : > "$MUTLOG"

# Minimal PATH: fake FIRST, then system dirs ONLY. Every dir a real grok could live in is excluded.
SAFEPATH="/usr/bin:/bin:/usr/sbin:/sbin"
CHILD_PATH="$FAKEBIN:$SAFEPATH"

# ------------------------------------------------------------------- extract shipped helpers
extract_fn() { awk -v fn="$1" '$0 ~ ("^" fn "\\(\\) \\($") {f=1} f{print} f && $0==")"{exit}' "$SKILL"; }
{ extract_fn grok_relay; echo; extract_fn grok_media; } > "$PRISTINE"
_hr=$(grep -c '^grok_relay() ($' "$PRISTINE"); _hm=$(grep -c '^grok_media() ($' "$PRISTINE")
if [ "$_hr" != 1 ] || [ "$_hm" != 1 ]; then
  echo "FATAL: could not extract exactly one grok_relay and one grok_media (relay=$_hr media=$_hm)" >&2; exit 2
fi
sh -n "$PRISTINE" 2>"$WORK/synerr" || { echo "FATAL: extracted helpers do not parse: $(cat "$WORK/synerr")" >&2; exit 2; }
for anchor in 'env -i' '\-\-deny' 'image_gen' 'GROK_AUTH_PATH' 'mktemp -d' 'trap ' 'set +eux' 'ln "$curtmp"' 'NO-HARDLINK-FAILCLOSED' 'manifest0' 'pending=' 'sbxreal' '_reappg' 'pgok' 'ps -o pgid=' 'case "$brief$out"' 'pwd -P' '_rollback' 'could not write config' '_ingit'; do
  grep -q "$anchor" "$PRISTINE" || { echo "FATAL: extracted helpers missing anchor: $anchor" >&2; exit 2; }
done

# --------------------------------------------------------------------------- generate fake grok
cat > "$FAKEBIN/grok.tmpl" <<'FAKE_EOF'
#!/bin/sh
# FAKE grok — generated by test-grok-runtime.sh. NOT the real grok. Makes no network call. Refuses to
# run unless the harness FILE sentinel is present (survives env -i, which strips env sentinels).
L='__LOGDIR__'
if [ ! -f "$L/SENTINEL" ]; then
  echo "FATAL fake-grok: sentinel absent at $L — refusing to run (guards a real grok invocation or PATH leak)." >&2
  exit 99
fi
printf '%s' "$$" > "$L/fake.pid"
# Adversarial: a temp-ENUMERATING malicious binary finds the wrapper's control base(s) (grok-ctl.*,
# which it was never given a path to) under the temp root and tampers with control/coordination files.
_troot=$(dirname "$(dirname "${TMPDIR:-/x/y}")")
if [ "$(cat "$L/spoof" 2>/dev/null || echo 0)" = 1 ]; then
  for _c in "$_troot"/grok-ctl.*; do [ -d "$_c" ] || continue; : > "$_c/done" 2>/dev/null; : > "$_c/timedout" 2>/dev/null; done
fi
_atk=$(cat "$L/attack" 2>/dev/null || echo none)
if [ "$_atk" != none ]; then
  for _c in "$_troot"/grok-ctl.*; do
    [ -d "$_c" ] || continue
    case "$_atk" in
      out_symlink)      rm -f "$_c/out" 2>/dev/null;      ln -s "$L/CANARY" "$_c/out" 2>/dev/null ;;
      out_fifo)         rm -f "$_c/out" 2>/dev/null;      mkfifo "$_c/out" 2>/dev/null ;;
      manifest_symlink) rm -f "$_c/manifest" 2>/dev/null; ln -s "$L/CANARY" "$_c/manifest" 2>/dev/null ;;
      manifest_fifo)    rm -f "$_c/manifest" 2>/dev/null; mkfifo "$_c/manifest" 2>/dev/null ;;
    esac
  done
fi
F="$L/$$.env"
isset() { eval "_v=\${$1+x}"; [ -n "${_v:-}" ] && printf '%s=set\n' "$1" || printf '%s=unset\n' "$1"; }
val()   { eval "_v=\${$1:-<UNSET>}"; printf '%s=%s\n' "$1" "$_v"; }
{
  echo "MARKER=FAKEGROK"
  val HOME; val GROK_HOME; val TMPDIR; val TERM; val PATH; val GROK_AUTH_PATH
  val GROK_TELEMETRY_ENABLED; val GROK_TELEMETRY_TRACE_UPLOAD; val GROK_EXTERNAL_OTEL
  # secrets: report set/unset only (never write a key VALUE to the log)
  isset XAI_API_KEY; isset GROK_CODE_XAI_API_KEY; isset GROK_AUTH; isset XAI_ROOT; isset XAI_USER
  isset GROK_DISABLE_API_KEY_AUTH
  # canaries that MUST NOT reach the child (set/unset)
  isset CANARY_SECRET; isset AWS_SECRET_ACCESS_KEY; isset GITHUB_TOKEN
  isset GROK_XAI_API_BASE_URL; isset XAI_API_BASE_URL; isset GROK_GATEWAY_URL; isset GROK_CLI_CHAT_PROXY_BASE_URL
  isset GROK_AUTH_PROVIDER_COMMAND; isset GROK_LOG_FILE; isset GROK_MANAGED_CONFIG; isset GROK_TRACE_UPLOAD_URL
  isset GROK_CLAUDE_SKILLS_ENABLED; isset GROK_CODEX_SESSIONS_ENABLED; isset GROK_FOLDER_TRUST
  echo "WSDC_VAL=${GROK_WORKSPACE_DATA_COLLECTION_DISABLED:-<UNSET>}"; isset GROK_SESSION_RECAP; isset GROK_FEEDBACK_ENABLED
  echo "PWD=$(pwd)"
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 && echo "IN_GIT=yes" || echo "IN_GIT=no"
  [ -e "${HOME:-/nope}/.claude" ] && echo "HOME_CLAUDE=yes" || echo "HOME_CLAUDE=no"
  [ -e "${HOME:-/nope}/.codex" ]  && echo "HOME_CODEX=yes"  || echo "HOME_CODEX=no"
  [ -e "${GROK_HOME:-/nope}/AGENTS.md" ] && echo "GH_AGENTS=yes" || echo "GH_AGENTS=no"
  cfg="${GROK_HOME:-/nope}/config.toml"
  if [ -f "$cfg" ]; then
    grep -q 'telemetry = false' "$cfg"  && echo "CFG_TELEMETRY=yes" || echo "CFG_TELEMETRY=no"
    grep -q 'trace_upload = false' "$cfg" && echo "CFG_TRACE=yes" || echo "CFG_TRACE=no"
    grep -q '\[compat.claude\]' "$cfg" && echo "CFG_CLAUDE=yes" || echo "CFG_CLAUDE=no"
    grep -q '\[compat.cursor\]' "$cfg" && echo "CFG_CURSOR=yes" || echo "CFG_CURSOR=no"
    grep -q '\[compat.codex\]' "$cfg"  && echo "CFG_CODEX=yes" || echo "CFG_CODEX=no"
    grep -q '^auto_update = false' "$cfg" && echo "CFG_AUTOUPDATE=yes" || echo "CFG_AUTOUPDATE=no"
    grep -q '^use_leader = false' "$cfg"  && echo "CFG_USELEADER=yes" || echo "CFG_USELEADER=no"
    printf 'CFG_SKILLS_FALSE_N=%s\n' "$(grep -c 'skills = false' "$cfg")"
    printf 'CFG_COMPAT_FALSE_N=%s\n' "$(grep -cE '^(skills|rules|agents|mcps|hooks|sessions) = false' "$cfg")"
  else echo "CFG_MISSING=yes"; fi
  echo "ARGV_BEGIN"; for _a in "$@"; do printf '%s\n' "$_a"; done; echo "ARGV_END"
} >> "$F"
# per-call overrides embedded in the prompt/brief argv (so concurrent calls can differ with one fake)
_rcovr=; _slpovr=; _amovr=
for _a in "$@"; do
  case "$_a" in *RCOVR=*)     _t=${_a##*RCOVR=};     _rcovr=${_t%%[!0-9]*} ;; esac
  case "$_a" in *SLEEPOVR=*)   _t=${_a##*SLEEPOVR=};  _slpovr=${_t%%[!0-9]*} ;; esac
  case "$_a" in *ARTMODE=*)    _t=${_a##*ARTMODE=};   _amovr=${_t%%[!a-z]*} ;; esac
done
# optional grandchild (for process-tree kill tests); duration overridable (short for the normal-exit limit demo)
[ "$(cat "$L/grandchild" 2>/dev/null || echo 0)" = 1 ] && { sleep "$(cat "$L/gcdur" 2>/dev/null || echo 55)" & printf '%s' "$!" > "$L/gc.pid"; }
# optional long turn (for timeout / signal tests)
_s=$(cat "$L/sleep" 2>/dev/null || echo 0); [ -n "$_slpovr" ] && _s=$_slpovr; [ "$_s" = 0 ] || sleep "$_s"
# media vs text
_media=0; for _a in "$@"; do [ "$_a" = "--tools" ] && _media=1; done
if [ "$_media" = 1 ]; then
  _d="${GROK_HOME:-.}/sessions/enc-$$"; mkdir -p "$_d/images"
  _am=$(cat "$L/artmode" 2>/dev/null || echo normal); [ -n "$_amovr" ] && _am=$_amovr
  case "$_am" in
    evil)  printf 'IMG\n' > "$_d/images/good.jpg"; _nm=$(printf 'decoy\nstealme.jpg'); : > "$_d/images/$_nm" 2>/dev/null ;;
    space) printf 'IMG\n' > "$_d/images/my art (v2).jpg" ;;
    *) _ic=$(cat "$L/imgcount" 2>/dev/null || echo 1); _vc=$(cat "$L/vidcount" 2>/dev/null || echo 0)
       _n=1; while [ "$_n" -le "$_ic" ] 2>/dev/null; do printf 'IMG-%s\n' "$_n" > "$_d/images/$_n.jpg"; _n=$((_n+1)); done
       _n=1; while [ "$_n" -le "$_vc" ] 2>/dev/null; do mkdir -p "$_d/videos"; printf 'VID-%s\n' "$_n" > "$_d/videos/$_n.mp4"; _n=$((_n+1)); done ;;
  esac
else
  echo "FAKE-GROK-ANSWER ok"
fi
_rc=$(cat "$L/rc" 2>/dev/null || echo 0); [ -n "$_rcovr" ] && _rc=$_rcovr; exit "$_rc"
FAKE_EOF
sed "s|__LOGDIR__|$LOGDIR|g" "$FAKEBIN/grok.tmpl" > "$FAKEBIN/grok"; chmod +x "$FAKEBIN/grok"; rm -f "$FAKEBIN/grok.tmpl"
: > "$LOGDIR/SENTINEL"
printf 'CANARY-CONTENT-DO-NOT-LEAK\n' > "$LOGDIR/CANARY"   # target for control-path symlink attacks

# safety gate at harness level
_resolved=$(PATH="$CHILD_PATH" command -v grok 2>/dev/null || true)
[ "$_resolved" = "$FAKEBIN/grok" ] || { echo "FATAL: 'grok' on the test PATH resolves to '$_resolved', not the fake. Aborting." >&2; exit 2; }

# ------------------------------------------------------------------------------ generate driver
cat > "$DRIVER" <<'DRIVER_EOF'
#!/bin/sh
SCN=${1:-}
setopt NO_NOMATCH 2>/dev/null || :   # zsh: a glob with no match expands to nothing (not a fatal error)
: "${WORK:?}"; : "${FAKEBIN:?}"; : "${LOGDIR:?}"; : "${HELPERS_FILE:?}"

# SAFETY (load-bearing): re-assert a minimal PATH with the fake FIRST, from INSIDE the script body —
# after any shell startup file (zsh sources ~/.zshenv even for `zsh script`, and a real ~/.zshenv
# commonly PREPENDS ~/.local/bin where the real grok lives). Every dir a real grok could live in is
# excluded, so `grok` can ONLY ever resolve to the fake. The gate then REFUSES to run if that fails.
PATH="$FAKEBIN:/usr/bin:/bin:/usr/sbin:/sbin"; export PATH
_g=$(command -v grok 2>/dev/null || true)
[ "$_g" = "$FAKEBIN/grok" ] || { echo "FAIL: SAFETY GATE — grok resolves to '$_g', not the fake; refusing"; exit 1; }

# scrub any real auth/key vars so branch selection is ours
unset XAI_API_KEY GROK_CODE_XAI_API_KEY GROK_AUTH_PATH GROK_AUTH XAI_ROOT XAI_USER GROK_HOME 2>/dev/null || true

run=$(mktemp -d "$WORK/runs/r.XXXXXX") || { echo "FAIL: mktemp run dir"; exit 1; }
realhome="$run/realhome"
export TMPDIR="$run/tmp"; mkdir -p "$TMPDIR"
# reset fake control files
printf 0 > "$LOGDIR/rc"; printf 0 > "$LOGDIR/sleep"; printf 1 > "$LOGDIR/imgcount"; printf 0 > "$LOGDIR/vidcount"; printf 0 > "$LOGDIR/grandchild"; printf 55 > "$LOGDIR/gcdur"; printf normal > "$LOGDIR/artmode"; printf 0 > "$LOGDIR/spoof"; printf none > "$LOGDIR/attack"; printf 'CANARY-CONTENT-DO-NOT-LEAK\n' > "$LOGDIR/CANARY"; rm -f "$LOGDIR/gc.pid" "$LOGDIR/fake.pid"
# clear per-call env logs (guard glob for zsh nomatch)
for _e in "$LOGDIR"/*.env; do [ -e "$_e" ] && rm -f "$_e"; done

. "$HELPERS_FILE" || { echo "FAIL: cannot source helpers"; exit 1; }

fail() { printf 'FAIL: %s\n' "$*"; exit 1; }
ok()   { printf 'PASS\n'; exit 0; }
skip() { printf 'SKIP: %s\n' "$*"; exit 2; }
# Can this shell put a backgrounded job in its OWN process group? sh/bash: yes. zsh rejects `set -m`
# non-interactively; dash turns job control off. This decides whether the wrapper can reap an ordinary
# descendant that survives grok's NORMAL/NONZERO exit (reparented to init but still in grok's group).
if ( set -m ) 2>/dev/null; then PGOK=1; else PGOK=0; fi
setup_home() {
  mkdir -p "$realhome/.grok/sessions" "$realhome/.claude" "$realhome/.codex"
  printf '{"xai":{"access_token":"CANARY-%s-DO-NOT-COPY"}}\n' "$(basename "$run")" > "$realhome/.grok/auth.json"
  printf 'REAL-CLAUDE-RULES\n' > "$realhome/.claude/CLAUDE.md"
  printf 'REAL-GROK-AGENTS\n'  > "$realhome/.grok/AGENTS.md"
  printf 'REAL-CODEX\n'        > "$realhome/.codex/AGENTS.md"
  export HOME="$realhome"
}
E() { for _x in "$LOGDIR"/*.env; do [ -e "$_x" ] && echo "$_x"; done | sort | tail -1; }
lg() { awk -F= -v k="$1" '$1==k{sub(/^[^=]*=/,"");print;exit}' "$(E)" 2>/dev/null; }
fake_ran() { for _x in "$LOGDIR"/*.env; do [ -e "$_x" ] && return 0; done; return 1; }
nfiles() { find "$1" -type f 2>/dev/null | wc -l | tr -d ' '; }
mkbrief() { _b="$run/brief-$1.md"; printf 'generate an %s asset; save under the cwd\n' "$1" > "$_b"; printf '%s' "$_b"; }

case "$SCN" in

text_happy)
  setup_home
  out=$(grok_relay "hello world" 2>"$run/err"); rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  fake_ran || fail "fake did not run"
  printf '%s' "$out" | grep -q 'FAKE-GROK-ANSWER' || fail "no answer on stdout: [$out]"
  [ "$(lg IN_GIT)" = no ] || fail "child ran inside git"
  ok ;;

media_happy)
  setup_home
  out=$(grok_media "$(mkbrief image)" "$run/out" 2>"$run/err"); rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  fake_ran || fail "fake did not run"
  c=$(nfiles "$run/out"); [ "$c" = 1 ] || fail "expected 1 artifact, got $c"
  printf '%s' "$out" | grep -q "^$run/out/" || fail "published path not under out: [$out]"
  ok ;;

canary_env)
  setup_home
  export CANARY_SECRET=leak-me AWS_SECRET_ACCESS_KEY=aws-leak GITHUB_TOKEN=gh-leak \
    GROK_XAI_API_BASE_URL=https://evil XAI_API_BASE_URL=https://evil2 GROK_GATEWAY_URL=https://evil3 \
    GROK_CLI_CHAT_PROXY_BASE_URL=https://evil4 GROK_AUTH_PROVIDER_COMMAND=/evil/cmd GROK_LOG_FILE=/evil/log \
    GROK_MANAGED_CONFIG=/evil/mc GROK_TRACE_UPLOAD_URL=https://evil5 GROK_CLAUDE_SKILLS_ENABLED=true \
    GROK_CODEX_SESSIONS_ENABLED=true GROK_FOLDER_TRUST=1 \
    GROK_SESSION_RECAP=1 GROK_FEEDBACK_ENABLED=1 GROK_AUTH=inline-leak XAI_ROOT=/leak XAI_USER=leaker
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  for v in CANARY_SECRET AWS_SECRET_ACCESS_KEY GITHUB_TOKEN GROK_XAI_API_BASE_URL XAI_API_BASE_URL \
           GROK_GATEWAY_URL GROK_CLI_CHAT_PROXY_BASE_URL GROK_AUTH_PROVIDER_COMMAND GROK_LOG_FILE \
           GROK_MANAGED_CONFIG GROK_TRACE_UPLOAD_URL GROK_CLAUDE_SKILLS_ENABLED GROK_CODEX_SESSIONS_ENABLED \
           GROK_FOLDER_TRUST GROK_SESSION_RECAP GROK_FEEDBACK_ENABLED \
           GROK_AUTH XAI_ROOT XAI_USER; do
    [ "$(lg "$v")" = unset ] || fail "SECURITY: $v reached the child (=$(lg "$v"))"
  done
  ok ;;

custom_grok_home)
  setup_home; mkdir -p "$run/customgrok"; cp "$realhome/.grok/auth.json" "$run/customgrok/auth.json"
  export GROK_HOME="$run/customgrok"; unset GROK_AUTH_PATH
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  [ "$(lg GROK_AUTH_PATH)" = "$run/customgrok/auth.json" ] || fail "auth not resolved via custom GROK_HOME: $(lg GROK_AUTH_PATH)"
  ok ;;

separate_dirs)
  setup_home
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  h=$(lg HOME); g=$(lg GROK_HOME); p=$(lg PWD)
  [ -n "$h" ] && [ -n "$g" ] && [ -n "$p" ] || fail "missing dir(s): HOME=$h GROK_HOME=$g PWD=$p"
  [ "$h" != "$g" ] || fail "HOME == GROK_HOME ($h)"
  [ "$h" != "$p" ] || fail "HOME == CWD ($h)"
  [ "$g" != "$p" ] || fail "GROK_HOME == CWD ($g)"
  ok ;;

xtrace_redact)
  setup_home; export XAI_API_KEY="TRACE-SECRET-9x"
  ( set -x; grok_relay "hi" >/dev/null; ) 2>"$run/xtrace"; rc=$?
  grep -q 'TRACE-SECRET-9x' "$run/xtrace" && fail "SECURITY: key value traced to stderr under set -x"
  ok ;;

repo_tmpdir_abort)
  setup_home; mkdir -p "$run/repo"; ( cd "$run/repo" && git init -q ) || fail "git init"
  export TMPDIR="$run/repo/inside"; mkdir -p "$TMPDIR"
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 1 ] || fail "expected abort (exit 1), got $rc"
  grep -q 'git worktree' "$run/err" || fail "no git-worktree abort message: [$(cat "$run/err")]"
  fake_ran && fail "SECURITY: grok ran despite CWD inside a git repo"
  ok ;;

repo_tmpdir_symlink_abort)
  setup_home; mkdir -p "$run/realrepo/sub"; ( cd "$run/realrepo" && git init -q ) || fail "git init"
  ln -s "$run/realrepo/sub" "$run/linktmp"          # TMPDIR is a SYMLINK into a git repo subdir
  export TMPDIR="$run/linktmp"
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 1 ] || fail "expected abort via symlinked TMPDIR into repo, got $rc (err: $(cat "$run/err"))"
  grep -q 'git worktree' "$run/err" || fail "no git-worktree abort message: [$(cat "$run/err")]"
  fake_ran && fail "SECURITY: grok ran despite a symlinked TMPDIR resolving inside a git repo"
  ok ;;

mktemp_fail)
  setup_home; export TMPDIR="$run/no/such/dir"     # does not exist -> mktemp -d fails
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 1 ] || fail "expected exit 1 on mktemp failure, got $rc"
  fake_ran && fail "grok ran despite mktemp failure"
  ok ;;

config_write_fail)
  setup_home
  ( umask 0777; grok_relay "q" >/dev/null 2>"$run/err" ); rc=$?   # subdirs created mode 000 -> config write fails
  [ "$rc" = 1 ] || fail "expected exit 1 on config-write failure, got $rc (err: $(cat "$run/err"))"
  fake_ran && fail "grok ran despite config-write failure"
  ok ;;

brief_unreadable)
  setup_home; b=$(mkbrief image); chmod 000 "$b"
  grok_media "$b" "$run/out" >/dev/null 2>"$run/err"; rc=$?; chmod 644 "$b" 2>/dev/null
  [ "$rc" = 2 ] || fail "expected exit 2 on unreadable brief, got $rc"
  fake_ran && fail "grok ran despite unreadable brief"
  ok ;;

sub_default_auth)
  setup_home; unset GROK_AUTH_PATH
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  [ "$(lg GROK_AUTH_PATH)" = "$realhome/.grok/auth.json" ] || fail "default auth path wrong: $(lg GROK_AUTH_PATH)"
  ok ;;

sub_custom_authpath)
  setup_home; mkdir -p "$run/c"; cp "$realhome/.grok/auth.json" "$run/c/auth.json"; export GROK_AUTH_PATH="$run/c/auth.json"
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc"
  [ "$(lg GROK_AUTH_PATH)" = "$run/c/auth.json" ] || fail "custom auth path not honored: $(lg GROK_AUTH_PATH)"
  ok ;;

sub_relative_auth)
  setup_home; mkdir -p "$run/rel/myauth"; cp "$realhome/.grok/auth.json" "$run/rel/myauth/auth.json"
  cd "$run/rel" || fail "cd"; export GROK_AUTH_PATH="myauth/auth.json"; want="$(pwd)/myauth/auth.json"
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc"
  [ "$(lg GROK_AUTH_PATH)" = "$want" ] || fail "relative auth not absolutised: $(lg GROK_AUTH_PATH) want $want"
  ok ;;

sub_failclosed)
  setup_home; rm -f "$realhome/.grok/auth.json"; unset GROK_AUTH_PATH
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 1 ] || fail "expected fail-closed exit 1, got $rc"
  grep -q 'no readable auth' "$run/err" || fail "no fail-closed message: [$(cat "$run/err")]"
  fake_ran && fail "SECURITY: grok ran despite missing auth"
  ok ;;

apikey_branch)
  setup_home; rm -f "$realhome/.grok/auth.json"; export XAI_API_KEY="SECRET-KEY-A1"
  out=$(grok_relay "hi" 2>"$run/err"); rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  [ "$(lg XAI_API_KEY)" = set ] || fail "child did not get XAI_API_KEY"
  [ "$(lg GROK_AUTH_PATH)" = "<UNSET>" ] || fail "GROK_AUTH_PATH present in api-key branch: $(lg GROK_AUTH_PATH)"
  grep -q 'SECRET-KEY-A1' "$run/err" && fail "SECURITY: key value on stderr"
  grep -rq 'SECRET-KEY-A1' "$LOGDIR"/*.env 2>/dev/null && fail "SECURITY: key value written to fake log"
  ok ;;

grokcode_key)
  setup_home; rm -f "$realhome/.grok/auth.json"; unset XAI_API_KEY; export GROK_CODE_XAI_API_KEY="SECRET-CODE-B2"
  grok_relay "hi" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  [ "$(lg XAI_API_KEY)" = set ] || fail "code-key did not trigger api-key branch (XAI_API_KEY not set in child)"
  [ "$(lg GROK_AUTH_PATH)" = "<UNSET>" ] || fail "GROK_AUTH_PATH present in code-key branch"
  ok ;;

config_content)
  setup_home
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc"
  [ "$(lg CFG_TELEMETRY)" = yes ] || fail "config missing telemetry=false"
  [ "$(lg CFG_TRACE)" = yes ] || fail "config missing trace_upload=false"
  [ "$(lg CFG_CLAUDE)" = yes ] || fail "config missing [compat.claude]"
  [ "$(lg CFG_CURSOR)" = yes ] || fail "config missing [compat.cursor]"
  [ "$(lg CFG_CODEX)" = yes ] || fail "config missing [compat.codex]"
  [ "$(lg CFG_AUTOUPDATE)" = yes ] || fail "config missing [cli] auto_update = false"
  [ "$(lg CFG_USELEADER)" = yes ] || fail "config missing [cli] use_leader = false"
  n=$(lg CFG_SKILLS_FALSE_N); [ "${n:-0}" -ge 3 ] || fail "expected >=3 'skills = false' (all vendors), got $n"
  cn=$(lg CFG_COMPAT_FALSE_N); [ "${cn:-0}" = 18 ] || fail "expected all 18 compat cells = false, got $cn"
  ok ;;

workspace_data_off)
  setup_home; export GROK_WORKSPACE_DATA_COLLECTION_DISABLED=false   # caller tries to ENABLE collection
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  [ "$(lg WSDC_VAL)" = true ] || fail "workspace data-collection not forced disabled in child (WSDC_VAL=$(lg WSDC_VAL))"
  ok ;;

env_scrub_telemetry)
  setup_home; export GROK_TELEMETRY_ENABLED=1 GROK_TELEMETRY_TRACE_UPLOAD=1 GROK_EXTERNAL_OTEL=1
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc"
  [ "$(lg GROK_TELEMETRY_ENABLED)" = false ] || fail "GROK_TELEMETRY_ENABLED not forced false (got $(lg GROK_TELEMETRY_ENABLED))"
  [ "$(lg GROK_TELEMETRY_TRACE_UPLOAD)" = false ] || fail "GROK_TELEMETRY_TRACE_UPLOAD not forced false"
  [ "$(lg GROK_EXTERNAL_OTEL)" = false ] || fail "GROK_EXTERNAL_OTEL not forced false"
  ok ;;

tool_flags_text)
  setup_home
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc"
  awk '/^ARGV_BEGIN$/{f=1;next} /^ARGV_END$/{f=0} f' "$(E)" > "$run/argv"
  grep -qx -- '--deny' "$run/argv" || fail "text: --deny absent"
  grep -qx -- '*' "$run/argv" || fail "text: deny-all '*' absent"
  grep -qx -- '--tools' "$run/argv" && fail "text: unexpected --tools"
  ok ;;

tool_flags_media)
  setup_home
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  awk '/^ARGV_BEGIN$/{f=1;next} /^ARGV_END$/{f=0} f' "$(E)" > "$run/argv"
  grep -qx -- '--tools' "$run/argv" || fail "media: --tools absent"
  grep -qx -- 'image_gen,image_edit,image_to_video,reference_to_video' "$run/argv" || fail "media: exact 4-tool allow-list absent"
  grep -qx -- '--disallowed-tools' "$run/argv" || fail "media: --disallowed-tools absent"
  grep -qx -- 'search_tool,use_tool' "$run/argv" || fail "media: disallowed meta-tools absent"
  grep -qx -- '--deny' "$run/argv" && fail "media: must NOT carry --deny"
  ok ;;

cwd_nongit_media)
  setup_home; mkdir -p "$run/repo"; ( cd "$run/repo" && git init -q ) || fail "git init"
  cd "$run/repo" || fail "cd repo"; mkdir -p "$run/repo/out"
  grok_media "$(mkbrief image)" "$run/repo/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  [ "$(lg IN_GIT)" = no ] || fail "SECURITY: media child ran inside a git repo"
  [ "$(lg PWD)" != "$run/repo/out" ] || fail "media child PWD == output dir"
  ok ;;

home_isolation)
  setup_home
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc"
  [ "$(lg HOME_CLAUDE)" = no ] || fail "child HOME has .claude"
  [ "$(lg HOME_CODEX)" = no ] || fail "child HOME has .codex"
  [ "$(lg GH_AGENTS)" = no ] || fail "child GROK_HOME has AGENTS.md"
  ok ;;

art_zero)
  setup_home; printf 0 > "$LOGDIR/imgcount"; printf 0 > "$LOGDIR/vidcount"
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" != 0 ] || fail "zero-artifact must be nonzero"
  c=$(nfiles "$run/out"); [ "$c" = 0 ] || fail "out not empty ($c)"
  ok ;;

art_multi)
  setup_home; printf 3 > "$LOGDIR/imgcount"
  out=$(grok_media "$(mkbrief image)" "$run/out" 2>"$run/err"); rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  c=$(nfiles "$run/out"); [ "$c" = 3 ] || fail "expected 3 artifacts, got $c"
  ok ;;

art_collision_file)
  setup_home; mkdir -p "$run/out"; printf 'ORIGINAL\n' > "$run/out/1.jpg"
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  grep -qx 'ORIGINAL' "$run/out/1.jpg" || fail "collision OVERWROTE existing 1.jpg"
  [ -f "$run/out/1-1.jpg" ] || fail "collision-safe rename missing (want 1-1.jpg); have: $(ls "$run/out")"
  c=$(nfiles "$run/out"); [ "$c" = 2 ] || fail "expected 2 files, got $c"
  ok ;;

art_dangling_symlink)
  setup_home; mkdir -p "$run/out"; ln -s "$run/no-such-target" "$run/out/1.jpg"
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  [ -e "$run/no-such-target" ] && fail "SECURITY: dangling symlink was FOLLOWED (target created)"
  [ -L "$run/out/1.jpg" ] || fail "dangling symlink was replaced/removed"
  [ -f "$run/out/1-1.jpg" ] || fail "collision-safe rename missing next to dangling symlink; have: $(ls -la "$run/out")"
  ok ;;

art_movefail)
  setup_home; mkdir -p "$run/out"; chmod 555 "$run/out"      # exists, not writable
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?; chmod 755 "$run/out"
  [ "$rc" != 0 ] || fail "publish-failure must be nonzero"
  c=$(nfiles "$run/out"); [ "$c" = 0 ] || fail "partial files left after publish-failure ($c)"
  grep -q 'rolled back' "$run/err" || fail "no rollback message: [$(cat "$run/err")]"
  ok ;;

ctl_out_symlink)
  setup_home; printf out_symlink > "$LOGDIR/attack"           # enumerating attacker symlinks $base/out -> canary
  out=$(grok_relay "q" 2>"$run/err"); rc=$?
  [ "$rc" = 1 ] || fail "expected fail-closed exit 1 on tampered answer file, got $rc"
  grep -q 'tampered' "$run/err" || fail "no tamper message: [$(cat "$run/err")]"
  printf '%s' "$out" | grep -q 'CANARY-CONTENT-DO-NOT-LEAK' && fail "SECURITY: symlinked out redirected the answer to the canary file"
  ok ;;

ctl_out_fifo)
  setup_home; printf out_fifo > "$LOGDIR/attack"              # FIFO at $base/out must not hang the read
  grok_relay "q" >/dev/null 2>"$run/err" & hp=$!
  i=0; while [ "$i" -lt 150 ] && kill -0 "$hp" 2>/dev/null; do sleep 0.1; i=$((i+1)); done
  kill -0 "$hp" 2>/dev/null && { kill -9 "$hp" 2>/dev/null; fail "SECURITY: relay HUNG on a FIFO planted at the control path"; }
  wait "$hp"; rc=$?
  [ "$rc" = 1 ] || fail "expected fail-closed exit 1 on FIFO answer file, got $rc"
  ok ;;

ctl_manifest_symlink)
  setup_home; printf manifest_symlink > "$LOGDIR/attack"      # symlink $base/manifest -> canary; rm-before-find must neutralize
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "media rc=$rc err=[$(cat "$run/err")] (manifest symlink should be rm'd before find)"
  grep -qx 'CANARY-CONTENT-DO-NOT-LEAK' "$LOGDIR/CANARY" || fail "SECURITY: find wrote through the symlinked manifest and truncated the canary"
  ok ;;

ctl_manifest_fifo)
  setup_home; printf manifest_fifo > "$LOGDIR/attack"         # FIFO at $base/manifest must not hang the write
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err" & hp=$!
  i=0; while [ "$i" -lt 150 ] && kill -0 "$hp" 2>/dev/null; do sleep 0.1; i=$((i+1)); done
  kill -0 "$hp" 2>/dev/null && { kill -9 "$hp" 2>/dev/null; fail "SECURITY: media HUNG on a FIFO planted at the manifest path"; }
  wait "$hp"; rc=$?
  [ "$rc" = 0 ] || fail "media rc=$rc after FIFO manifest (should rm+recreate)"
  ok ;;

publish_dest_symlink)
  setup_home; mkdir -p "$run/out"; ln -s "$LOGDIR/CANARY" "$run/out/1.jpg"   # pre-existing symlink at the target name
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "media rc=$rc err=[$(cat "$run/err")]"
  [ -L "$run/out/1.jpg" ] || fail "pre-existing symlink was replaced (must be left untouched)"
  grep -qx 'CANARY-CONTENT-DO-NOT-LEAK' "$LOGDIR/CANARY" || fail "SECURITY: publish followed the symlink and clobbered the canary target"
  [ -f "$run/out/1-1.jpg" ] || fail "artifact not published under a fresh name; have: $(ls -la "$run/out")"
  ok ;;

rollback_creates_out)
  # grok fails -> the whole call rolls back. The output dir this call CREATED is deliberately NOT removed
  # (removing it could race a concurrent call about to publish there); it is left EMPTY. Assert: nonzero
  # exit + NO partial artifacts in the created dir.
  setup_home; printf 7 > "$LOGDIR/rc"
  grok_media "$(mkbrief image)" "$run/newout" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" != 0 ] || fail "expected nonzero on grok failure"
  c=$(nfiles "$run/newout" 2>/dev/null); [ "${c:-0}" = 0 ] || fail "created output dir left with $c partial file(s) after rollback"
  ok ;;

publish_sig_int)  _sig=INT;  _pubsig ;;
publish_sig_term) _sig=TERM; _pubsig ;;
publish_sig_hup)  _sig=HUP;  _pubsig ;;

descendant_normal_exit)
  # Reaping an ordinary backgrounded descendant that survives grok's NORMAL exit is intentionally NOT
  # provided: the post-wait negative process-group kill was removed (grok is already dead by then and its
  # pgid could be reused). Descendant reaping is guaranteed ONLY while grok is still alive — the
  # signal/timeout paths: timeout / watchdog_spoof / sig_* / publish_sig_* / dash_pgid_safety. Documented
  # SKIP (out of scope; needs an OS sandbox — see SECURITY.md). Skips before launch, so nothing leaks.
  skip "normal-exit descendant reaping not provided (only signal/timeout, while grok is alive); see SECURITY.md" ;;

descendant_nonzero_exit)
  # Same as descendant_normal_exit for the nonzero path (media still rolls back + exits 3, verified by
  # art_grokfail; a descendant that outlives grok's own exit is not reaped). Documented SKIP.
  skip "nonzero-exit descendant reaping not provided (only signal/timeout, while grok is alive); see SECURITY.md" ;;

art_grokfail)
  setup_home; printf 7 > "$LOGDIR/rc"
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" != 0 ] || fail "grok-nonzero must be nonzero"
  c=$(nfiles "$run/out"); [ "$c" = 0 ] || fail "artifacts not rolled back ($c)"
  grep -q 'rolled back' "$run/err" || fail "no rollback message"
  ok ;;

timeout)
  setup_home; printf 8 > "$LOGDIR/sleep"; printf 1 > "$LOGDIR/grandchild"; export GROK_RELAY_TIMEOUT=1
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 124 ] || fail "expected timeout exit 124, got $rc (err: $(cat "$run/err"))"
  gc=$(cat "$LOGDIR/gc.pid" 2>/dev/null || true)
  [ -n "$gc" ] && { kill -0 "$gc" 2>/dev/null && { kill -9 "$gc" 2>/dev/null; fail "grandchild $gc alive after timeout"; } || : ; }
  ls -d "$TMPDIR"/grok-ctl.* "$TMPDIR"/grok-sbx.* >/dev/null 2>&1 && fail "leftover temp dir after timeout"
  ok ;;

watchdog_spoof)
  setup_home; printf 1 > "$LOGDIR/spoof"; printf 8 > "$LOGDIR/sleep"; printf 1 > "$LOGDIR/grandchild"; export GROK_RELAY_TIMEOUT=1
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 124 ] || fail "SECURITY: grok disarmed the watchdog via a spoofed \$base marker (expected 124, got $rc)"
  gc=$(cat "$LOGDIR/gc.pid" 2>/dev/null || true)
  [ -n "$gc" ] && kill -0 "$gc" 2>/dev/null && { kill -9 "$gc" 2>/dev/null; fail "grandchild alive after spoofed-watchdog timeout"; }
  ls -d "$TMPDIR"/grok-ctl.* "$TMPDIR"/grok-sbx.* >/dev/null 2>&1 && fail "leftover temp after spoofed-watchdog timeout"
  ok ;;

sig_int)  _sig=INT;  _sigtest ;;
sig_term) _sig=TERM; _sigtest ;;
sig_hup)  _sig=HUP;  _sigtest ;;

concurrency_samedir)
  setup_home; mkdir -p "$run/out"
  ( grok_media "$(mkbrief a)" "$run/out" >/dev/null 2>"$run/e1"; echo $? > "$run/rc1" ) &
  ( grok_media "$(mkbrief b)" "$run/out" >/dev/null 2>"$run/e2"; echo $? > "$run/rc2" ) &
  wait
  [ "$(cat "$run/rc1" 2>/dev/null)" = 0 ] || fail "call1 rc=$(cat "$run/rc1" 2>/dev/null) err=$(cat "$run/e1")"
  [ "$(cat "$run/rc2" 2>/dev/null)" = 0 ] || fail "call2 rc=$(cat "$run/rc2" 2>/dev/null) err=$(cat "$run/e2")"
  c=$(nfiles "$run/out"); [ "$c" = 2 ] || fail "expected 2 distinct artifacts in shared dir, got $c ($(ls "$run/out"))"
  ok ;;

set_eu_success)
  setup_home
  ( set -eu; grok_relay "hi" >/dev/null 2>"$run/e"; case "$-" in *e*) : ;; *) exit 20 ;; esac; case "$-" in *u*) : ;; *) exit 21 ;; esac; exit 0 ); rc=$?
  [ "$rc" = 0 ] || fail "set -eu caller aborted or lost options (rc=$rc)"
  ok ;;

set_eu_usage)
  setup_home
  ( set -eu; if grok_relay >/dev/null 2>"$run/e"; then r=0; else r=$?; fi; [ "$r" = 2 ] || exit 30; exit 0 ); rc=$?
  [ "$rc" = 0 ] || fail "usage under set -eu killed caller or wrong code (rc=$rc)"
  grep -q 'usage' "$run/e" || fail "missing usage message"
  ok ;;

sentinel_untouched)
  setup_home
  before=$(find "$realhome/.claude" "$realhome/.grok" -type f 2>/dev/null | sort | while IFS= read -r f; do printf '%s:%s\n' "$f" "$(cksum "$f")"; done)
  grok_relay "q" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc"
  printf 2 > "$LOGDIR/imgcount"; grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err2"; rc2=$?
  [ "$rc2" = 0 ] || fail "media rc=$rc2"
  after=$(find "$realhome/.claude" "$realhome/.grok" -type f 2>/dev/null | sort | while IFS= read -r f; do printf '%s:%s\n' "$f" "$(cksum "$f")"; done)
  [ "$before" = "$after" ] || fail "real-home protected files changed by the wrapper"
  grep -rq 'CANARY.*DO-NOT-COPY' "$run/out" "$LOGDIR"/*.env 2>/dev/null && fail "SECURITY: auth token CONTENT copied into artifact/log"
  ok ;;

spaces_metachars)
  setup_home; bdir="$run/dir with spaces & \$x"; mkdir -p "$bdir"; brief="$bdir/my brief (v2).md"
  printf 'draw a cat; rm -rf / ; echo $HOME `id`\n' > "$brief"; odir="$run/out dir \$y"
  grok_media "$brief" "$odir" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "media w/ spaces+metachars rc=$rc err=[$(cat "$run/err")]"
  c=$(nfiles "$odir"); [ "$c" = 1 ] || fail "artifact count $c in spacey out"
  grok_relay 'hello $USER; `id`; a b c' >/dev/null 2>"$run/err2"; rc2=$?
  [ "$rc2" = 0 ] || fail "relay w/ metachars rc=$rc2 err=[$(cat "$run/err2")]"
  ok ;;

media_timeout)
  setup_home; printf 8 > "$LOGDIR/sleep"; export GROK_MEDIA_TIMEOUT=1
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 124 ] || fail "media timeout must exit 124 (distinct from publish-fail 3), got $rc (err: $(cat "$run/err"))"
  grep -q 'timed out' "$run/err" || fail "no timeout message: [$(cat "$run/err")]"
  c=$(nfiles "$run/out"); [ "$c" = 0 ] || fail "artifacts left after media timeout ($c)"
  ok ;;

newline_failclosed)
  # A malicious grok names an artifact with an embedded newline (whose 2nd manifest line would match a
  # caller-CWD file). The wrapper must FAIL CLOSED *before* publishing anything: nonzero, nothing written,
  # and no caller-CWD file exfiltrated. Silently skipping it and returning 0 is NOT accepted.
  setup_home; cd "$run" || fail "cd"; printf 'STEAL-ME-SECRET\n' > "$run/stealme.jpg"; printf evil > "$LOGDIR/artmode"
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" != 0 ] || fail "SECURITY: newline-named artifact NOT fail-closed (rc=0 — silent skip)"
  grep -q 'newline' "$run/err" || fail "no fail-closed newline message: [$(cat "$run/err")]"
  grep -rq 'STEAL-ME-SECRET' "$run/out" 2>/dev/null && fail "SECURITY: caller-CWD file exfiltrated via newline-split manifest"
  [ -f "$run/stealme.jpg" ] || fail "caller-CWD file was moved/removed"
  c=$(nfiles "$run/out" 2>/dev/null); [ "${c:-0}" = 0 ] || fail "partial artifacts published before fail-closed ($c: $(ls "$run/out"))"
  ok ;;

artifact_spacename)
  setup_home; printf space > "$LOGDIR/artmode"
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" = 0 ] || fail "rc=$rc err=[$(cat "$run/err")]"
  [ -f "$run/out/my art (v2).jpg" ] || fail "space/metachar artifact name not published verbatim; have: $(ls "$run/out")"
  c=$(nfiles "$run/out"); [ "$c" = 1 ] || fail "expected 1 artifact, got $c"
  ok ;;

concurrent_rollback_isolation)
  # OUTPUT-DIR does NOT pre-exist. Call B (fails after a delay) and call A (succeeds) race into it. B's
  # rollback must NOT destroy A's successful artifact and must NOT rm -rf the now-shared dir.
  setup_home; odir="$run/co"
  printf 'gen image SLEEPOVR=3 RCOVR=7\n' > "$run/bB.md"
  printf 'gen image SLEEPOVR=0 RCOVR=0\n' > "$run/bA.md"
  ( grok_media "$run/bB.md" "$odir" >/dev/null 2>"$run/eB"; echo $? > "$run/rcB" ) &
  ( sleep 0.5; grok_media "$run/bA.md" "$odir" >/dev/null 2>"$run/eA"; echo $? > "$run/rcA" ) &
  wait
  [ "$(cat "$run/rcA" 2>/dev/null)" = 0 ] || fail "success call A rc=$(cat "$run/rcA" 2>/dev/null) err=$(cat "$run/eA")"
  [ "$(cat "$run/rcB" 2>/dev/null)" != 0 ] || fail "fail call B must be nonzero (got $(cat "$run/rcB" 2>/dev/null))"
  c=$(nfiles "$odir"); [ "${c:-0}" -ge 1 ] || fail "SECURITY: B's rollback destroyed A's successful output (dir has ${c:-0} files: $(ls -la "$odir" 2>/dev/null))"
  ok ;;

nohl_failclosed)
  # No-hardlink filesystem emulation: disable `ln` so it always fails with the name free. There is NO
  # safe atomic no-replace fallback in pure shell (reserve-then-fill re-opens the path and can follow a
  # swapped symlink; mv clobbers), so the wrapper must FAIL CLOSED: nonzero, and nothing published.
  setup_home
  sed 's@ln "$curtmp" "$dest" 2>/dev/null@false@' "$HELPERS_FILE" > "$run/nohl.sh" || fail "sed"
  sh -n "$run/nohl.sh" || fail "nohl variant does not parse"
  . "$run/nohl.sh"
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" != 0 ] || fail "SECURITY: no-hardlink path PUBLISHED instead of failing closed (rc=0)"
  c=$(nfiles "$run/out" 2>/dev/null); [ "${c:-0}" = 0 ] || fail "no-hardlink path left $c published file(s) — must be fail-closed"
  ok ;;

rollback_preserves_preexisting)
  # Rollback must delete ONLY files THIS call created, never a PRE-EXISTING one — even on a name
  # collision. Pre-create 1.jpg (as if another call owns it); grok fails; this call publishes 1-1.jpg then
  # rolls back. 1.jpg must survive byte-identical; 1-1.jpg must be gone.
  setup_home; mkdir -p "$run/out"; printf 'PREEXISTING-OWNED-BY-OTHER\n' > "$run/out/1.jpg"; printf 7 > "$LOGDIR/rc"
  grok_media "$(mkbrief image)" "$run/out" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" != 0 ] || fail "expected nonzero (grok failed)"
  grep -qx 'PREEXISTING-OWNED-BY-OTHER' "$run/out/1.jpg" || fail "SECURITY: rollback deleted/altered a PRE-EXISTING file"
  [ -e "$run/out/1-1.jpg" ] && fail "this call's published artifact 1-1.jpg was not rolled back"
  ok ;;

concurrent_reverse_timing)
  # REVERSE timing: the FAILING call creates the dir first (out_pre=0); the SUCCESSFUL call sees it and is
  # mid-run when the failing call rolls back. A buggy rmdir/rm-rf on rollback would remove the still-empty
  # shared dir and break the successful call's later publish. With no-dir-removal rollback the success call
  # must publish fine. B fails ~1s (creates + rolls back the dir); A publishes ~3s (wide, deterministic margin).
  setup_home; odir="$run/rt"
  printf 'gen image SLEEPOVR=1 RCOVR=7\n' > "$run/bB.md"
  printf 'gen image SLEEPOVR=3 RCOVR=0\n' > "$run/bA.md"
  ( grok_media "$run/bB.md" "$odir" >/dev/null 2>"$run/eB"; echo $? > "$run/rcB" ) &
  ( sleep 0.3; grok_media "$run/bA.md" "$odir" >/dev/null 2>"$run/eA"; echo $? > "$run/rcA" ) &
  wait
  [ "$(cat "$run/rcA" 2>/dev/null)" = 0 ] || fail "SECURITY/reverse-timing: success call A broken by B's rollback (rc=$(cat "$run/rcA" 2>/dev/null), err=$(cat "$run/eA"))"
  c=$(nfiles "$odir" 2>/dev/null); [ "${c:-0}" -ge 1 ] || fail "success call A published nothing into the shared dir ($c)"
  ok ;;

newline_output_dir)
  # An OUTPUT-DIR path containing a newline must be refused BEFORE any file/dir is created, so it can
  # never be split into two rollback targets. Deterministic (no sleep); a neighbor path sitting on the
  # 2nd line of the newline-split value must be left untouched, and grok must not even launch.
  setup_home
  nl=$(printf '\nx'); nl=${nl%x}
  printf 'NEIGHBOR-KEEP\n' > "$run/keep"
  odir="$run/evildir${nl}$run/keep"
  grok_media "$(mkbrief image)" "$odir" >/dev/null 2>"$run/err"; rc=$?
  [ "$rc" != 0 ] || fail "newline OUTPUT-DIR not rejected (rc=0)"
  grep -q 'newline' "$run/err" || fail "no newline-refusal message: [$(cat "$run/err")]"
  grep -qx 'NEIGHBOR-KEEP' "$run/keep" || fail "SECURITY: neighbor path on the 2nd line was touched"
  [ -e "$run/evildir" ] && fail "partial output dir created from a newline path"
  fake_ran && fail "grok launched despite a newline OUTPUT-DIR (must reject before launch)"
  ok ;;

dash_pgid_safety)
  # BEHAVIORAL: run the SHIPPED helper under dash with a `kill` SHIM that RECORDS negative (process-group)
  # kills but never delivers them (so a bug/mutation can't signal the harness or unrelated groups), and
  # delivers only positive/liveness kills — to the test-owned fake-grok tree. Force the still-alive
  # signal-cleanup path via a short timeout (fake sleeps 8s, GROK_RELAY_TIMEOUT=1) so the watchdog runs
  # `_reappg` while grok is alive; any negative kill it attempts is observed. Under dash `set -m` yields
  # no per-job group, so the helper's `pgid==child` guard keeps pgok=0 -> it must attempt NO negative
  # kill. The AB mutation (drop the guard) makes pgok=1 -> a negative kill IS attempted -> recorded -> FAIL.
  command -v dash >/dev/null 2>&1 || skip "dash not installed"
  setup_home
  klog="$run/killlog.dash"; : > "$klog"
  printf 8 > "$LOGDIR/sleep"; printf 1 > "$LOGDIR/grandchild"; printf 30 > "$LOGDIR/gcdur"
  dash -c '
    KILLLOG="'"$klog"'"
    kill() { for __a in "$@"; do case "$__a" in -[1-9]*) printf "%s\n" "$*" >> "$KILLLOG"; return 0 ;; esac; done; command kill "$@"; }
    PATH="'"$FAKEBIN"':/usr/bin:/bin:/usr/sbin:/sbin"; export PATH
    HOME="'"$realhome"'"; export HOME; TMPDIR="'"$run/tmp"'"; export TMPDIR
    unset XAI_API_KEY GROK_CODE_XAI_API_KEY GROK_AUTH_PATH GROK_AUTH GROK_HOME 2>/dev/null || true
    . "'"$HELPERS_FILE"'" || exit 97
    GROK_RELAY_TIMEOUT=1 grok_relay "q" >/dev/null 2>&1
    exit 0
  ' 2>/dev/null
  [ -s "$klog" ] && fail "SECURITY: helper attempted an unverified negative process-group kill under dash: [$(cat "$klog")]"
  gc=$(cat "$LOGDIR/gc.pid" 2>/dev/null || true); [ -n "$gc" ] && kill -9 "$gc" 2>/dev/null   # reap any real fake tree (owned exact PIDs)
  fp=$(cat "$LOGDIR/fake.pid" 2>/dev/null || true); [ -n "$fp" ] && kill -9 "$fp" 2>/dev/null
  ok ;;

*) fail "unknown scenario: $SCN" ;;
esac
DRIVER_EOF

# _sigtest is appended before the case dispatch so it exists when a sig_* scenario is invoked.
cat > "$WORK/sigtest.sh" <<'SIG_EOF'
# Deliver INT/TERM/HUP to the helper's OWN main subshell (the parent of grok) — the process a
# foreground Ctrl-C reaches via the terminal's process group — and assert the helper's trap reaps its
# whole tree (grok + grandchild + watchdog) and removes its temp base. The helper runs in the
# FOREGROUND (so INT is not shell-ignored, unlike a backgrounded async job) while a background watcher
# sends exactly ONE signal to that subshell. The harness never kills grok or the grandchild itself —
# the helper's own trap does. (A backgrounded `grok_relay ... &` killed via $! instead hits the shell's
# intermediate wrapper subshell, not the trap; that path is covered by the watchdog timeout — see the
# `timeout` scenario and the LIMITATIONS note.)
_sigtest() {
  setup_home; printf 30 > "$LOGDIR/sleep"; printf 1 > "$LOGDIR/grandchild"; rm -f "$LOGDIR/fake.pid" "$LOGDIR/gc.pid"
  ( j=0; while [ "$j" -lt 300 ]; do { [ -s "$LOGDIR/fake.pid" ] && [ -s "$LOGDIR/gc.pid" ]; } && break; sleep 0.05; j=$((j+1)); done
    fp=$(cat "$LOGDIR/fake.pid" 2>/dev/null || true); [ -n "$fp" ] || exit 0
    s2=$(ps -o ppid= -p "$fp" 2>/dev/null | tr -d ' '); [ -n "$s2" ] && kill -"$_sig" "$s2" 2>/dev/null ) &
  watcher=$!
  grok_relay "long turn" >/dev/null 2>"$run/err"; rc=$?
  wait "$watcher" 2>/dev/null
  gc=$(cat "$LOGDIR/gc.pid" 2>/dev/null || true)
  i=0; while [ "$i" -lt 100 ]; do ls -d "$TMPDIR"/grok-ctl.* "$TMPDIR"/grok-sbx.* >/dev/null 2>&1 || break; sleep 0.05; i=$((i+1)); done
  ls -d "$TMPDIR"/grok-ctl.* "$TMPDIR"/grok-sbx.* >/dev/null 2>&1 && fail "leftover temp dir after $_sig (rc=$rc)"
  [ -n "$gc" ] && kill -0 "$gc" 2>/dev/null && { kill -9 "$gc" 2>/dev/null; fail "orphaned grandchild alive after $_sig"; }
  ok
}

# Deliver $_sig to the helper's trap-bearing subshell DURING the publish loop (after grok has exited).
# The helper runs in the FOREGROUND — exactly the case a real Ctrl-C hits — because a BACKGROUNDED shell
# job sets INT/QUIT to SIG_IGN, so INT to a `& job would be dropped (a test artifact, not a wrapper bug).
# A background watcher captures the trap-bearer PID = grok's PARENT (owned/parent-verified: grok's pid is
# written by our own fake) WHILE grok is alive, then signals THAT pid once publish has started. Never a
# process-name match, never grok itself. The trap must roll back THIS call's partials and, since it
# created OUTPUT-DIR, remove it when empty; and leave no control/sandbox base behind.
_pubsig() {
  setup_home; printf 1 > "$LOGDIR/sleep"; printf 120 > "$LOGDIR/imgcount"; rm -f "$LOGDIR/fake.pid"
  odir="$run/sig-$_sig-out"                                  # does NOT pre-exist -> out_pre=0
  ( tb=""; j=0
    while [ "$j" -lt 400 ]; do fp=$(cat "$LOGDIR/fake.pid" 2>/dev/null || true)
      [ -n "$fp" ] && { tb=$(ps -o ppid= -p "$fp" 2>/dev/null | tr -d ' '); [ -n "$tb" ] && break; }
      sleep 0.02; j=$((j+1)); done
    [ -n "$tb" ] || exit 0
    j=0; while [ "$j" -lt 1500 ]; do [ -n "$(find "$odir" -mindepth 1 2>/dev/null)" ] && break; sleep 0.02; j=$((j+1)); done
    kill -"$_sig" "$tb" 2>/dev/null ) &
  wp=$!
  grok_media "$(mkbrief image)" "$odir" >/dev/null 2>"$run/err"; rc=$?
  wait "$wp" 2>/dev/null; sleep 0.4
  # Real failures ALWAYS fail: the helper's control + sandbox temp bases must be gone.
  ls -d "$TMPDIR"/grok-ctl.* "$TMPDIR"/grok-sbx.* >/dev/null 2>&1 && fail "$_sig: leftover control/sandbox base after publish signal"
  # Classify OUTPUT-DIR residue against the accepted scope. A VISIBLE (published) artifact left behind =
  # rollback failure = FAIL. Only a HIDDEN .grokpub.* temp = the known local-only mktemp-assignment signal
  # window (a signal after mktemp creates the temp but before $curtmp is assigned): NOT external egress,
  # NOT user-data loss -> clean the exact test-owned residue and record a documented SKIP. No residue = PASS.
  if [ -d "$odir" ]; then
    vis=$(find "$odir" -type f ! -name '.grokpub.*' 2>/dev/null | wc -l | tr -d ' ')
    [ "${vis:-0}" = 0 ] || fail "$_sig: visible/published artifact left after signal during publish ($(ls "$odir"))"
    if [ "$(find "$odir" -type f -name '.grokpub.*' 2>/dev/null | wc -l | tr -d ' ')" != 0 ]; then
      find "$odir" -type f -name '.grokpub.*' -exec rm -f {} + 2>/dev/null   # clean the exact test-owned residue
      skip "known local-only mktemp assignment signal window; no external egress or source-data loss"
    fi
  fi
  ok
}
SIG_EOF
awk 'NR==FNR{s=s $0 ORS; next} /^fail\(\) \{/ && !d {printf "%s", s; d=1} {print}' "$WORK/sigtest.sh" "$DRIVER" > "$DRIVER.new" && mv "$DRIVER.new" "$DRIVER"

# ------------------------------------------------------------------------------- run one case
run_case() { HELPERS_FILE="$3" WORK="$WORK" FAKEBIN="$FAKEBIN" LOGDIR="$LOGDIR" PATH="$CHILD_PATH" "$1" "$DRIVER" "$2" 2>&1; }

SHELLS=""
for cand in sh bash zsh; do p=$(command -v "$cand" 2>/dev/null || true); [ -n "$p" ] && SHELLS="$SHELLS $cand:$p"; done

SCENARIOS="text_happy media_happy canary_env custom_grok_home separate_dirs xtrace_redact \
repo_tmpdir_abort repo_tmpdir_symlink_abort mktemp_fail config_write_fail brief_unreadable sub_default_auth sub_custom_authpath \
sub_relative_auth sub_failclosed apikey_branch grokcode_key config_content workspace_data_off env_scrub_telemetry \
tool_flags_text tool_flags_media cwd_nongit_media home_isolation art_zero art_multi art_collision_file \
art_dangling_symlink art_movefail art_grokfail ctl_out_symlink ctl_out_fifo ctl_manifest_symlink ctl_manifest_fifo \
publish_dest_symlink rollback_creates_out timeout watchdog_spoof sig_int sig_term sig_hup concurrency_samedir \
set_eu_success set_eu_usage sentinel_untouched spaces_metachars \
descendant_normal_exit descendant_nonzero_exit publish_sig_int publish_sig_term publish_sig_hup \
media_timeout newline_failclosed artifact_spacename concurrent_rollback_isolation nohl_failclosed rollback_preserves_preexisting concurrent_reverse_timing \
newline_output_dir dash_pgid_safety"

echo "=================================================================================="
echo " grok_relay / grok_media — RUNTIME isolation proof (M6, fake grok, no network)"
echo "=================================================================================="
echo " SKILL.md  : $SKILL"
echo " fake grok : $FAKEBIN/grok   (child PATH: $CHILD_PATH)"
printf " shells    :"; for e in $SHELLS; do printf ' %s' "${e%%:*}"; done; [ -z "$SHELLS" ] && printf ' (none!)'; echo; echo

FAILS=0
for scn in $SCENARIOS; do
  for cand in sh bash zsh; do
    ent=""; for e in $SHELLS; do [ "${e%%:*}" = "$cand" ] && ent=$e; done
    if [ -z "$ent" ]; then printf '%s|%s|SKIP|shell not installed\n' "$scn" "$cand" >> "$RESULTS"; continue; fi
    out=$(run_case "${ent#*:}" "$scn" "$PRISTINE"); LASTRC=$?
    if [ "$LASTRC" = 0 ]; then printf '%s|%s|PASS|\n' "$scn" "$cand" >> "$RESULTS"
    elif [ "$LASTRC" = 2 ]; then reason=$(printf '%s' "$out" | grep '^SKIP:' | head -1 | sed 's/^SKIP: //'); printf '%s|%s|SKIP|%s\n' "$scn" "$cand" "$reason" >> "$RESULTS"
    else FAILS=$((FAILS+1)); reason=$(printf '%s' "$out" | grep '^FAIL:' | head -1 | sed 's/^FAIL: //'); [ -z "$reason" ] && reason=$(printf '%s' "$out" | head -1)
      printf '%s|%s|FAIL|%s\n' "$scn" "$cand" "$reason" >> "$RESULTS"; fi
  done
done

# ------------------------------------------------------------------------ mutation red-green
MUTSHELL=""; for e in $SHELLS; do case "$e" in bash:*) MUTSHELL=${e#*:} ;; esac; done
[ -z "$MUTSHELL" ] && for e in $SHELLS; do case "$e" in sh:*) MUTSHELL=${e#*:} ;; esac; done
[ -z "$MUTSHELL" ] && for e in $SHELLS; do MUTSHELL=${e#*:}; done
MUTFAILS=0
run_mut() {
  _id=$1; _desc=$2; _scn=$3; _prog=$4; _mut="$WORK/helpers.mut.$_id.sh"
  sed "$_prog" "$PRISTINE" > "$_mut"
  if ! sh -n "$_mut" 2>/dev/null; then printf '%s|%s|%s|MUT-SYNTAX-ERR|-\n' "$_id" "$_desc" "$_scn" >> "$MUTLOG"; MUTFAILS=$((MUTFAILS+1)); return; fi
  _o=$(run_case "$MUTSHELL" "$_scn" "$_mut"); _red=$?
  run_case "$MUTSHELL" "$_scn" "$PRISTINE" >/dev/null 2>&1; _green=$?
  if [ "$_red" != 0 ] && [ "$_green" = 0 ]; then _v=OK; else _v=BROKEN; MUTFAILS=$((MUTFAILS+1)); fi
  _why=$(printf '%s' "$_o" | grep '^FAIL:' | head -1 | sed 's/^FAIL: //')
  printf '%s|%s|%s|%s|%s\n' "$_id" "$_desc" "$_scn" "$_v" "$_why" >> "$MUTLOG"
}
if [ -n "$MUTSHELL" ]; then
  run_mut A "hermetic env -i -> plain env (blocklist)"     canary_env          's/env -i /env /g'
  run_mut B "child HOME -> caller real HOME"               home_isolation      's/HOME="$hm"/HOME="$HOME"/g'
  run_mut C "child GROK_HOME -> real ~/.grok"              home_isolation      's#GROK_HOME="$gkh"#GROK_HOME="$HOME/.grok"#g'
  run_mut D "text --deny '*' removed"                      tool_flags_text     "s/ --deny '\\*'//g"
  run_mut E "media allow-list widened (+search_tool)"      tool_flags_media    's/reference_to_video"/reference_to_video,search_tool"/g'
  run_mut F "zero-artifact guard removed"                  art_zero            's/ || \[ -z "$published" \]//g'
  run_mut G "watchdog timeout removed"                     timeout             '/( __n=0; __max=/,/^  wd=\$!$/d'
  run_mut H "media CWD isolation removed (runs in OUT)"    cwd_nongit_media    's/cd "$iso" \&\& exec env/cd "$out" \&\& exec env/g'
  run_mut I "telemetry env-scrub removed"                  env_scrub_telemetry 's/GROK_TELEMETRY_ENABLED=false GROK_TELEMETRY_TRACE_UPLOAD=false GROK_EXTERNAL_OTEL=false //g'
  run_mut J "xtrace not disabled (set +eux -> +eu)"        xtrace_redact       's/set +eux/set +eu/g'
  run_mut K "git-worktree check removed"                   repo_tmpdir_abort   's/_ingit "$iso" \&\&/false \&\&/g'
  run_mut N "git-check uses lexical path (misses symlink)" repo_tmpdir_symlink_abort 's#__d=$(cd "$1" 2>/dev/null && pwd -P) || __d=$1#__d=$1#g'
  run_mut O "watchdog trusts a grok-writable done file"    watchdog_spoof      's#do kill -0 "$child" 2>/dev/null || exit 0;#do [ -f "$base/done" ] \&\& exit 0; kill -0 "$child" 2>/dev/null || exit 0;#g'
  run_mut P "workspace-data-collection disable dropped"    workspace_data_off  's#GROK_WORKSPACE_DATA_COLLECTION_DISABLED=true ##g'
  run_mut Q "[cli] auto_update=false line deleted"         config_content      '/^auto_update = false$/d'
  run_mut R "[compat.codex] section deleted"               config_content      '/^\[compat.codex\]$/,/^sessions = false$/d'
  run_mut S "answer-file integrity check removed"          ctl_out_symlink     's#{ \[ -f "$base/out" \] && \[ ! -L "$base/out" \]; }#true#'
  run_mut T "manifest rm-before-find removed"              ctl_manifest_symlink 's#rm -f "$base/manifest" "$base/manifest0" 2>/dev/null##'
  run_mut U "publish uses clobbering ln -f (follows dest)" publish_dest_symlink 's#ln "$curtmp" "$dest"#ln -f "$curtmp" "$dest"#g'
  run_mut V "rollback re-adds rmdir of created dir (reverse-timing hazard)" concurrent_reverse_timing 's#\[ -n "${curtmp:-}" \] && rm -f "$curtmp" 2>/dev/null#[ -n "${curtmp:-}" ] \&\& rm -f "$curtmp" 2>/dev/null; [ "${out_pre:-1}" = 0 ] \&\& rmdir "$out" 2>/dev/null#'
  run_mut W "rollback re-adds rm -rf of output dir (destroys concurrent output)" concurrent_rollback_isolation 's#\[ -n "${curtmp:-}" \] && rm -f "$curtmp" 2>/dev/null#[ -n "${curtmp:-}" ] \&\& rm -f "$curtmp" 2>/dev/null; [ "${out_pre:-1}" = 0 ] \&\& rm -rf "$out" 2>/dev/null#'
  run_mut X "newline fail-closed check disabled" newline_failclosed 's#    _rollback; exit 3#    :#'
  run_mut Y "no-hardlink path publishes (clobbering mv) instead of failing closed" nohl_failclosed '/NO-HARDLINK-FAILCLOSED/{n;s@fail=1; break@mv "$curtmp" "$dest" 2>/dev/null \&\& { pending="$dest"; break; } || { fail=1; break; }@;}'
  run_mut Z "media timeout collapses to generic exit 3 (not 124)" media_timeout 's#if \[ "$rc" = 124 \]; then exit 124; fi#:#'
  run_mut AA "newline-in-OUTPUT-DIR guard disabled" newline_output_dir 's@\*"$__nl"\*)@*"ZZNOMATCHZZ"*)@'
  run_mut AB "pgid==child verification dropped (unverified negative kill)" dash_pgid_safety 's#\[ "$__pg" = "$child" \] && pgok=1#pgok=1#g'
fi

# --------------------------------------------------------------------------------- reporting
echo "---------------------------------------------------------------------------------"
echo " SCENARIO MATRIX  (PASS / FAIL / SKIP)"
echo "---------------------------------------------------------------------------------"
printf ' %-22s %-6s %-6s %-6s\n' scenario sh bash zsh
cellof() { awk -F'|' -v s="$1" -v sh="$2" '$1==s && $2==sh {print $3; f=1} END{if(!f)print "?"}' "$RESULTS"; }
for scn in $SCENARIOS; do printf ' %-22s %-6s %-6s %-6s\n' "$scn" "$(cellof "$scn" sh)" "$(cellof "$scn" bash)" "$(cellof "$scn" zsh)"; done
echo
if [ "$FAILS" -gt 0 ]; then echo " FAILURES:"; awk -F'|' '$3=="FAIL"{printf "   [%s/%s] %s\n",$1,$2,$4}' "$RESULTS"; echo; fi

echo "---------------------------------------------------------------------------------"
echo " MUTATION RED-GREEN  (mutate a COPY; scenario must FAIL mutated, PASS pristine)"
echo "---------------------------------------------------------------------------------"
printf ' %-3s %-44s %-20s %-7s\n' id mutation scenario verdict
if [ -s "$MUTLOG" ]; then while IFS='|' read -r id desc scn v why; do printf ' %-3s %-44s %-20s %-7s\n' "$id" "$desc" "$scn" "$v"; [ -n "$why" ] && printf '     caught by: %s\n' "$why"; done < "$MUTLOG"; else echo " (no shells for mutations)"; fi
echo

cnt() { c=$(grep -c "$1" "$2" 2>/dev/null); [ -n "$c" ] || c=0; printf '%s' "$c"; }
nuniq=$(echo $SCENARIOS | wc -w | tr -d ' ')
nshell=0; for e in $SHELLS; do nshell=$((nshell+1)); done
npass=$(cnt '|PASS|' "$RESULTS"); nfail=$(cnt '|FAIL|' "$RESULTS"); nskip=$(cnt '|SKIP|' "$RESULTS")
nmut=$(wc -l < "$MUTLOG" 2>/dev/null | tr -d ' '); [ -n "$nmut" ] || nmut=0; nmutok=$(cnt '|OK|' "$MUTLOG")
echo "---------------------------------------------------------------------------------"
echo " SUMMARY"
echo "---------------------------------------------------------------------------------"
printf ' unique scenarios : %s\n' "$nuniq"
printf ' shells available : %s (%s)\n' "$nshell" "$(for e in $SHELLS; do printf '%s ' "${e%%:*}"; done)"
printf ' matrix cells     : %s PASS / %s FAIL / %s SKIP  (of %s scenario x shell)\n' "$npass" "$nfail" "$nskip" "$((nuniq * 3))"
printf ' mutations        : %s/%s caught (red-green OK)\n' "$nmutok" "$nmut"
echo
echo " LIMITATIONS (cannot be proven with a fake runtime):"
echo "  - The shipped grok binary is NOT verified; this proves only the WRAPPER's isolation."
echo "  - No real network/xAI call; upstream auth refresh / catalog fetch is unexercised."
echo "  - Timeout is exercised by a fake long turn + the helper's own watchdog (not a real hang)."
echo "  - Signal cleanup is asserted via trap outcome (no leftover temp / no orphan), sending the"
echo "    signal to the HELPER (not by the harness killing child PIDs)."
echo "  - Cross-filesystem publish is covered by the copy-based design + the publish-failure rollback"
echo "    test (art_movefail); a true two-filesystem test is not run here."

if [ "$FAILS" -gt 0 ] || [ "$MUTFAILS" -gt 0 ]; then
  echo; echo "RESULT: FAIL ($FAILS scenario failures, $MUTFAILS mutation red-green failures)"; exit 1
fi
echo; echo "RESULT: PASS ($npass passed / $nfail failed / $nskip documented skip(s), of $((nuniq * 3)) cells; $nmutok/$nmut mutations caught)"; exit 0
